name: angel3_client
version: 8.0.0
description: A browser, mobile and command line based client that supports querying Angel3 servers
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/client
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_http_exception: ^8.0.0
  belatuk_json_serializer: ^7.0.0
  collection: ^1.17.0
  http: ^1.0.0
  meta: ^1.9.0
  path: ^1.8.0
  logging: ^1.1.0
dev_dependencies:
  angel3_framework: ^8.0.0
  angel3_model: ^8.0.0
  angel3_mock_request: ^8.0.0
  angel3_container: ^8.0.0
  angel3_auth: ^8.0.0
  async: ^2.11.0
  quiver: ^3.2.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  test: ^1.24.0
  lints: ^2.1.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_auth:
#     path: ../auth