name: angel3_route
version: 8.1.1
description: A powerful, isomorphic routing library for Dart. It is mainly used in the Angel3 framework, but can be used in Flutter and on the Web.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/route
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  belatuk_combinator: ^5.1.0
  string_scanner: ^1.2.0
  path: ^1.8.0
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  http: ^1.0.0
  test: ^1.24.0
  lints: ^4.0.0
