name: angel3_route
version: 7.0.0
description: A powerful, isomorphic routing library for Dart. It is mainly used in the Angel3 framework, but can be used in Flutter and on the Web.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/route
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  belatuk_combinator: ^4.0.0
  string_scanner: ^1.1.0
  path: ^1.8.0
dev_dependencies:
  build_runner: ^2.1.2
  build_web_compilers: ^3.2.1
  http: ^0.13.3
  test: ^1.21.0
  lints: ^2.0.0
