name: angel3_sync
version: 8.1.1
description: Easily synchronize and scale WebSockets using belatuk_pub_sub in Angel3.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/angel3/packages/sync
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  angel3_framework: ^8.0.0
  angel3_websocket: ^8.0.0
  belatuk_pub_sub: ^6.1.0
  stream_channel: ^2.1.0
dev_dependencies:
  angel3_test: ^8.0.0
  test: ^1.24.0
  lints: ^4.0.0
# dependency_overrides:
#   angel3_websocket:
#     path: ../websocket
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_auth:
#     path: ../auth 
#   angel3_client:
#     path: ../client
#   angel3_test:
#     path: ../test
#   angel3_validate:
#     path: ../validate