name: data_loader
version: 1.0.0
author: Tobe O <thosakwe@gmail.com>
description: Batch and cache database lookups. Works well with GraphQL. Ported from JS.
homepage: https://github.com/angel-dart/graphql
environment:
  sdk: '>=2.10.0 <2.12.0'
dev_dependencies:
  graphql_schema: #^1.0.0
    path: ../graphql_schema
  pedantic: ^1.0.0
  test: ^1.15.7