name: angel3_hot
version: 8.2.0
description: Supports hot reloading/hot code push of Angel3 servers on file changes.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/hot
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_framework: ^8.2.0
  angel3_websocket: ^8.1.0
  belatuk_html_builder: ^5.1.0
  charcode: ^1.3.0
  glob: ^2.1.0
  io: ^1.0.0
  path: ^1.9.0
  vm_service: ^14.0.0
  watcher: ^1.0.0
  logging: ^1.2.0
dev_dependencies:
  http: ^1.0.0
  lints: ^3.0.0
#dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#  angel3_framework:
#    path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_auth:
#     path: ../auth
#   angel3_client:
#     path: ../client
#   angel3_websocket:
#     path: ../websocket
 