name: angel3_hot
version: 7.0.1
description: Supports hot reloading/hot code push of Angel3 servers on file changes.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/hot
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  angel3_framework: ^7.0.0
  angel3_websocket: ^7.0.0
  belatuk_html_builder: ^4.0.0
  charcode: ^1.2.0
  glob: ^2.0.1
  io: ^1.0.0
  path: ^1.8.0
  vm_service: ^9.3.0
  watcher: ^1.0.0
dev_dependencies:
  http: ^0.13.2
  logging: ^1.0.1
  lints: ^2.0.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_auth:
#     path: ../auth
#   angel3_client:
#     path: ../client
#   angel3_websocket:
#     path: ../websocket
 