name: angel_seeder
version: 2.0.0
description: Straightforward data seeder for Angel services.
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
homepage: https://github.com/angel-dart/seeder
dependencies:
  angel_framework:
   git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/framework
  faker: ^2.0.0
dev_dependencies:
    test: ^1.17.8
    lints: ^1.0.0
