name: angel3_framework
version: 8.0.0
description: A high-powered HTTP server extensible framework with dependency injection, routing and much more.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/framework
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_container: ^8.0.0
  angel3_http_exception: ^8.0.0
  angel3_model: ^8.0.0
  angel3_route: ^8.0.0
  angel3_mock_request: ^8.0.0
  belatuk_merge_map: ^5.0.0
  belatuk_combinator: ^5.0.0
  belatuk_http_server: ^4.0.0
  charcode: ^1.3.0
  file: ^7.0.0
  http_parser: ^4.0.0
  http2: ^2.0.0
  logging: ^1.1.0
  matcher: ^0.12.16
  meta: ^1.9.0
  mime: ^1.0.0
  path: ^1.8.0
  quiver: ^3.2.0
  recase: ^4.1.0
  stack_trace: ^1.11.0
  string_scanner: ^1.2.0
  tuple: ^2.0.0
  uuid: ^3.0.0
  collection: ^1.17.0
dev_dependencies:
  http: ^1.0.0
  io: ^1.0.0
  test: ^1.24.0
  lints: ^2.1.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request

