name: angel3_framework
version: 6.0.0
description: A high-powered HTTP server extensible framework with dependency injection, routing and much more.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/framework
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  angel3_container: ^6.0.0
  angel3_http_exception: ^6.0.0
  angel3_model: ^6.0.0
  angel3_route: ^6.0.0
  angel3_mock_request: ^6.0.0
  belatuk_merge_map: ^3.0.0
  belatuk_combinator: ^3.0.0
  belatuk_http_server: ^2.1.0
  charcode: ^1.2.0
  file: ^6.1.0
  http_parser: ^4.0.0
  http2: ^2.0.0
  logging: ^1.0.0
  matcher: ^0.12.10
  meta: ^1.3.0
  mime: ^1.0.0
  path: ^1.8.0
  quiver: ^3.0.1
  recase: ^4.0.0
  stack_trace: ^1.10.0
  string_scanner: ^1.1.0
  tuple: ^2.0.0
  uuid: ^3.0.1
  collection: ^1.15.0
dev_dependencies:
  http: ^0.13.1
  io: ^1.0.0
  test: ^1.21.0
  lints: ^1.0.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
