name: angel3_user_agent
version: 7.0.0-beta.1
description: Angel3 middleware to parse and inject a User Agent object into requests.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/user_agent/angel_user_agent
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  angel3_framework: ^7.0.0
  user_agent_analyzer: ^3.0.0
  lints: ^2.0.0
# dependency_overrides:
#   angel3_container:
#     path: ../../container/angel_container
#   angel3_http_exception:
#     path: ../../http_exception
#   angel3_model:
#     path: ../../model
#   angel3_route:
#     path: ../../route
#   angel3_mock_request:
#     path: ../../mock_request
#   angel3_framework:
#     path: ../../framework