name: angel3_orm_test
version: 7.1.0
description: Common tests for Angel3 ORM. Reference implmentation of the generated ORM files.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/orm/angel_orm_test
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  angel3_migration: ^7.0.0
  angel3_model: ^7.0.0
  angel3_orm: ^7.0.0
  angel3_serialize: ^7.0.0
  io: ^1.0.0
  test: ^1.21.0
  collection: ^1.15.0
  optional: ^6.0.0
dev_dependencies:
  angel3_orm_generator: ^7.0.0
  angel3_framework: ^7.0.0
  build_runner: ^2.0.1
  lints: ^2.0.0
# dependency_overrides:
#   angel3_container:
#     path: ../../container/angel_container
#   angel3_framework:
#     path: ../../framework
#   angel3_http_exception:
#     path: ../../http_exception
#   angel3_model:
#     path: ../../model
#   angel3_route:
#     path: ../../route
#   angel3_mock_request:
#     path: ../../mock_request
#   angel3_serialize:
#     path: ../../serialize/angel_serialize
#   angel3_serialize_generator:
#      path: ../../serialize/angel_serialize_generator
#   angel3_orm:
#      path: ../angel_orm
#   angel3_migration:
#      path: ../angel_migration
#  angel3_orm_generator:
#    path: ../angel_orm_generator
