name: angel3_jinja
version: 8.3.1
description: A service that renders Jinja2 template into HTML view for Angel3. Ported from Python to Dart.
homepage: https://github.com/dart-backend/angel/tree/master/packages/jinja
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  angel3_framework: ^8.4.0
  jinja: ^0.6.0
dev_dependencies:
  angel3_test: ^8.2.0
  path: ^1.9.0
  test: ^1.24.0
  lints: ^4.0.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_test:
#     path: ../test
#   angel3_websocket:
#     path: ../websocket
#   angel3_client:
#     path: ../client
#   angel3_auth:
#     path: ../auth
#   angel3_validate:
#     path: ../validate