name: angel3_container
version: 7.1.0-beta.2
description: Angel3 hierarchical DI container, and pluggable backends for reflection.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/container/angel_container
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  collection: ^1.17.0
  quiver: ^3.2.0
dev_dependencies:
  test: ^1.24.0
  lints: ^2.0.0