name: angel3_html
version: 8.0.0
description: Support for rendering html_builder AST's as responses in Angel.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/angel3/packages/html_builder
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  angel3_framework: ^8.0.0
  belatuk_html_builder: ^5.0.0
dev_dependencies:
  angel3_test: ^8.0.0
  html: ^0.15.0
  logging: ^1.0.1
  test: ^1.21.0
  lints: ^3.0.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_test:
#     path: ../test
#   angel3_websocket:
#     path: ../websocket
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_client:
#     path: ../client
#   angel3_auth:
#     path: ../auth 
#   angel3_validate:
#     path: ../validate
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
