name: angel3_oauth2
version: 7.0.0
description: A class containing handlers that can be used within Angel to build a spec-compliant OAuth 2.0 server.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/oauth2
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  angel3_framework: ^7.0.0
  angel3_http_exception: ^7.0.0
  crypto: ^3.0.1
  collection: ^1.15.0
dev_dependencies: 
  angel3_validate: ^7.0.0
  angel3_test: ^7.0.0
  logging: ^1.0.1
  oauth2: ^2.0.0
  lints: ^2.0.0
  test: ^1.21.0
  uuid: ^3.0.4
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_test:
#     path: ../test
#   angel3_validate:
#     path: ../validate
#   angel3_websocket:
#     path: ../websocket
#   angel3_client:
#     path: ../client
#   angel3_auth:
#     path: ../auth