name: angel3_cors
version: 6.0.0
description: Angel3 CORS middleware. Ported from expressjs/cors to Angel3 framework.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/cors
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  angel3_framework: ^6.0.0
dev_dependencies:
  angel3_test: ^6.0.0
  http: ^0.13.3
  lints: ^1.0.0
  test: ^1.17.5
dependency_overrides:
  angel3_container:
    path: ../container/angel_container
  angel3_framework:
    path: ../framework
  angel3_http_exception:
    path: ../http_exception
  angel3_model:
    path: ../model
  angel3_route:
    path: ../route
  angel3_mock_request:
    path: ../mock_request
  angel3_auth:
    path: ../auth
  angel3_client:
    path: ../client
  angel3_websocket:
    path: ../websocket
  angel3_validate:
    path: ../validate
  angel3_test:
    path: ../test
