name: angel3_cors
version: 8.2.0
description: Angel3 CORS middleware. Ported from expressjs/cors to Angel3 framework.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/cors
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies: 
  angel3_framework: ^8.0.0
dev_dependencies:
  angel3_test: ^8.0.0
  http: ^1.0.0
  lints: ^4.0.0
  test: ^1.24.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_auth:
#     path: ../auth
#   angel3_client:
#     path: ../client
#   angel3_websocket:
#     path: ../websocket
#   angel3_validate:
#     path: ../validate
#   angel3_test:
#     path: ../test
