name: angel_auth
description: A complete authentication plugin for Angel. Includes support for stateless JWT tokens, Basic Auth, and more.
version: 4.0.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_auth
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/framework
  charcode: ^1.2.0
  collection: ^1.15.0
  crypto: ^3.0.0
  http_parser: ^4.0.0
  meta: ^1.3.0
  quiver: ^3.0.0
dev_dependencies:
  http: ^0.13.1
  io: ^1.0.0
  logging: ^1.0.0
  pedantic: ^1.11.0
  test: ^1.16.8
