name: angel3_auth
description: A complete authentication plugin for Angel3. Includes support for stateless JWT tokens, Basic Auth, and more.
version: 7.0.0
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/auth
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  angel3_framework: ^7.0.0
  charcode: ^1.2.0
  collection: ^1.15.0
  crypto: ^3.0.0
  http_parser: ^4.0.0
  meta: ^1.3.0
  quiver: ^3.0.0
  logging: ^1.0.0
dev_dependencies:
  angel3_container: ^7.0.0
  http: ^0.13.1
  io: ^1.0.0
  test: ^1.21.0
  lints: ^2.0.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#   angel3_framework:
#     path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request