name: angel3_auth_oauth2
version: 7.0.0
description: Angel3 library for authenticating users with external identity providers via OAuth2.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/auth_oauth2
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  angel3_auth: ^7.0.0
  angel3_framework: ^7.0.0
  http_parser: ^4.0.0
  oauth2: ^2.0.0
dev_dependencies:
  logging: ^1.0.1
  lints: ^2.0.0
dependency_overrides:
  angel3_container:
    path: ../container/angel_container
  angel3_framework:
    path: ../framework
  angel3_auth:
    path: ../auth
