name: jael3
version: 6.0.0
description:  A simple server-side HTML templating engine for Dart. Comparable to Blade or Liquid.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/jael/jael
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  args: ^2.0.0
  charcode: ^1.0.0
  belatuk_code_buffer: ^3.0.0
  belatuk_symbol_table: ^3.0.0
  source_span: ^1.0.0
  string_scanner: ^1.0.0
  collection: ^1.15.0
  matcher: ^0.12.10 
dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.0
executables:
  jaelfmt: jaelfmt