name: angel3_body_parser
version: 2.0.0
description: Parse request bodies and query strings in Dart. Supports JSON, URL-encoded, and multi-part bodies.
homepage: https://github.com/dukefirehawk/angel/tree/angel3/packages/body_parser
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  http_parser: ^4.0.0
  http_server: ^1.0.0
  mime: ^1.0.0
dev_dependencies:
  http: ^0.13.0
  test: ^1.17.0
  pedantic: ^1.11.0