name: angel3_static
version: 6.0.0
description: This library provides a virtual directory to serve static files for Angel3 framework.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/static
environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  angel3_framework: ^6.0.0
  belatuk_range_header: ^4.0.0
  convert: ^3.0.0
  crypto: ^3.0.1
  file: ^6.1.0
  http_parser: ^4.0.0
  path: ^1.8.0
  logging: ^1.0.1
dev_dependencies:
  angel3_test: ^6.0.0
  http: ^0.13.2
  matcher: ^0.12.10
  lints: ^1.0.0
  test: ^1.17.4
dependency_overrides:
  angel3_container:
    path: ../container/angel_container
  angel3_framework:
    path: ../framework
  angel3_http_exception:
    path: ../http_exception
  angel3_model:
    path: ../model
  angel3_route:
    path: ../route
  angel3_mock_request:
    path: ../mock_request
  angel3_auth:
    path: ../auth 
  angel3_client:
    path: ../client
  angel3_websocket:
    path: ../websocket
  angel3_validate:
    path: ../validate
  angel3_test:
    path: ../test
  
