name: angel3_migration_runner
version: 8.3.0
description: The implementation of database migration for Angel3 framework. Designed to work with Angel3 ORM.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/orm/angel_migration_runner
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  angel3_migration: ^8.3.0
  angel3_orm: ^8.2.0
  args: ^2.4.0
  charcode: ^1.3.0
  postgres: ^3.0.0
  mysql_client: ^0.0.27
  mysql1: ^0.20.0
  logging: ^1.2.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
# dependency_overrides:
#    angel3_orm:
#      path: ../angel_orm
#    angel3_migration:
#      path: ../angel_migration
