name: angel3_model
version: 8.0.0
description: Angel3 basic data model class, no longer with the added weight of the whole framework.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/model
environment:
  sdk: '>=3.0.0 <4.0.0'
dev_dependencies:
  lints: ^2.1.0
