name: jael3_language_server
version: 8.0.0
description: Language Server Protocol implementation for the Jael templating engine.
homepage: https://github.com/angel-dart/vscode
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.4.0
#  dart_language_server: ^0.1.16
  file: ^7.0.0
  io: ^1.0.0
  jael3: ^8.0.0
  jael3_preprocessor: ^8.0.0
  belatuk_symbol_table: ^5.0.0
  json_rpc_2: ^3.0.0
  logging: ^1.2.0
  path: ^1.8.0
  source_span: ^1.10.0
  string_scanner: ^1.2.0
  lints: ^2.1.0
  stream_channel: ^2.1.0
  async: ^2.11.0
executables:
  jael3_language_server: jael3_language_server
# dependency_overrides:
#   jael3:
#     path: ../jael
#   jael3_preprocessor:
#     path: ../jael_preprocessor
