name: jael3_web
version: 8.2.0
description: Experimental virtual DOM/SPA engine built on Jael3. Supports SSR.
publish_to: none
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  analyzer: ^6.2.0
  build: ^2.0.2
  build_config: ^1.0.0
  code_builder: ^4.0.0
  file: ^7.0.0
  path: ^1.8.0
  jael3: ^8.0.0
  jael3_preprocessor: ^8.0.0
  source_gen: ^1.3.0
dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^4.0.0
# dependency_overrides:
#   jael3:
#     path: ../jael
#   jael3_preprocessor:
#     path: ../jael_preprocessor
