name: angel3_orm_mysql
version: 2.0.0-beta.3
description: MySQL support for Angel3 ORM. Includes functionality for querying and transactions.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/orm/angel_orm_mysql
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  angel3_orm: ^4.0.0
  logging: ^1.0.0
  pool: ^1.5.0
  galileo_sqljocky5: ^3.0.0
  optional: ^6.0.0
dev_dependencies:
  angel3_migration: ^4.0.0
  angel3_orm_generator: ^4.0.0
  build_runner: ^2.0.0
  test: ^1.17.0
  angel3_orm_test: ^3.0.0
  lints: ^1.0.0
dependency_overrides:
  angel3_orm_test:
    path: ../angel_orm_test
  angel3_orm:
    path: ../angel_orm

