name: angel3_websocket
version: 7.0.0
description: This library provides WebSockets support for Angel3 framework.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/websocket
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  angel3_auth: ^7.0.0
  angel3_client: ^7.0.0
  angel3_framework: ^7.0.0
  angel3_http_exception: ^7.0.0
  belatuk_merge_map: ^4.0.0
  http: ^0.13.1
  meta: ^1.3.0
  stream_channel: ^2.1.0
  web_socket_channel: ^2.1.0
  collection: ^1.15.0
  logging: ^1.0.1
dev_dependencies:
  angel3_container: ^7.0.0
  angel3_model: ^7.0.0
  test: ^1.21.0
  lints: ^2.0.0
# dependency_overrides:
#   angel3_container:
#     path: ../container/angel_container
#    angel3_framework:
#      path: ../framework
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
#   angel3_auth:
#     path: ../auth 
#   angel3_client:
#     path: ../client