name: angel3_mock_request
version: 8.1.1
description: Manufacture dart:io HttpRequests, HttpResponses, HttpHeaders, etc.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/mock_request
environment:
    sdk: '>=3.3.0 <4.0.0'
dependencies:
  charcode: ^1.3.0
dev_dependencies:
  #angel3_framework: ^7.0.0
  http: ^1.0.0
  test: ^1.24.0
  lints: ^4.0.0
# dependency_overrides:
#   angel3_framework:
#     path: ../framework
#   angel3_route:
#     path: ../route
#   angel3_model:
#     path: ../model
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_container:
#     path: ../container/angel_container