name: angel3_proxy
version: 7.0.0
description: Angel middleware to forward requests to another server (i.e. pub serve).
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/proxy
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  angel3_framework: ^7.0.0
  http: ^0.13.3
  http_parser: ^4.0.0
  path: ^1.8.0
dev_dependencies:
  angel3_test: ^7.0.0
  angel3_mock_request: ^7.0.0
  logging: ^1.0.1
  lints: ^2.0.0
  test: ^1.21.0
dependency_overrides:
  angel3_framework:
    path: ../framework
  angel3_container:
    path: ../container/angel_container
  angel3_http_exception:
    path: ../http_exception
  angel3_model:
    path: ../model
  angel3_route:
    path: ../route
  angel3_mock_request:
    path: ../mock_request
  angel3_test:
    path: ../test
  angel3_websocket:
    path: ../websocket
  angel3_client:
    path: ../client
  angel3_auth:
    path: ../auth
  angel3_validate:
    path: ../validate