name: angel3_orm
version: 4.0.6
description: Runtime support for Angel3 ORM. Includes base classes for queries.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/orm/angel_orm
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  charcode: ^1.2.0
  intl: ^0.17.0
  meta: ^1.3.0
  string_scanner: ^1.1.0
  optional: ^6.0.0
  logging: ^1.0.0
dev_dependencies:
  angel3_model: ^3.0.0
  angel3_serialize: ^4.1.0
  angel3_serialize_generator: ^4.1.0
  build_runner: ^2.1.1
  test: ^1.17.4
  lints: ^1.0.0