name: angel3_sembast
version: 8.1.1
description: A plugin service that persist data to Sembast for Angel3 framework.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/sembast
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  angel3_framework: ^8.0.0
  sembast: ^3.1.1
dev_dependencies:
  angel3_http_exception: ^8.0.0
  logging: ^1.2.0
  lints: ^4.0.0
  test: ^1.24.0
# dependency_overrides:
#   angel3_framework:
#     path: ../framework
#   angel3_container:
#     path: ../container/angel_container
#   angel3_http_exception:
#     path: ../http_exception
#   angel3_model:
#     path: ../model
#   angel3_route:
#     path: ../route
#   angel3_mock_request:
#     path: ../mock_request
