name: angel_file_service
version: 3.0.0
description: Angel service that persists data to a file on disk.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/file_service
publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  angel_framework:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/framework
  file: ^6.1.0
  pool: ^1.0.0
dev_dependencies:
  test: ^1.16.5