#author: Tobe O <thosakwe@gmail.com>
description: Command-line tools for the Angel framework, including scaffolding.
homepage: https://github.com/dukefirehawk/angel/packages/angel_cli
name: angel_cli
version: 2.3.0
environment: 
  sdk: ">=2.10.0 <3.0.0"
dependencies: 
  analyzer: ^1.1.0
  args: ^2.0.0
  code_builder: ^3.0.0
  dart_style: ^1.0.0
  glob: ^2.0.0
  http: ^0.13.0
  io: ^0.3.5
  inflection2: ^0.4.2
  mustache4dart2: ^0.1.0
  path: ^1.0.0
  prompts: ^1.3.1
  pubspec_parse: ^1.0.0
  quiver: ^3.0.0
  recase: ^3.0.1
  shutdown: ^0.4.0
  watcher: ^1.0.0
  yaml: ^3.0.0
executables: 
  angel: angel
