name: angel3_validate
description: Cross-platform request body validation library based on `matcher`.
version: 7.0.0
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/validate
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  angel3_framework: ^7.0.0
  angel3_http_exception: ^7.0.0
  matcher: ^0.12.0
dev_dependencies:
  angel3_mock_request: ^7.0.0
  build_runner: ^2.1.0
  build_web_compilers: ^3.2.0
  logging: ^1.0.1
  lints: ^2.0.0
  test: ^1.21.0
dependency_overrides:
  angel3_container:
    path: ../container/angel_container
  angel3_framework:
    path: ../framework
  angel3_http_exception:
    path: ../http_exception
  angel3_model:
    path: ../model
  angel3_route:
    path: ../route
  angel3_mock_request:
    path: ../mock_request