name: angel3_serialize_generator
version: 8.3.0
description: Angel3 model serialization generators, designed for use with Angel. Combine with angel_serialize for flexible modeling.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/serialize/angel_serialize_generator
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  analyzer: ^6.2.0
  angel3_model: ^8.0.0
  angel3_serialize: ^8.0.0
  belatuk_code_buffer: ^5.1.0
  build: ^2.0.1
  build_config: ^1.0.0
  code_builder: ^4.0.0
  meta: ^1.9.0
  path: ^1.9.0
  recase: ^4.0.0
  source_gen: ^1.0.0
  quiver: ^3.0.1
  logging: ^1.2.0
dev_dependencies:
  build_runner: ^2.0.1
  collection: ^1.17.0
  lints: ^4.0.0
  test: ^1.24.0
# dependency_overrides:
#   angel3_model:
#     path: ../../model
#   angel3_serialize:
#     path: ../angel_serialize
