name: angel3_serialize_generator
version: 4.2.0
description: Angel3 model serialization generators, designed for use with Angel. Combine with angel_serialize for flexible modeling.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/angel3/packages/serialize/angel_serialize_generator
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  analyzer: ^2.0.0
  angel3_model: ^3.0.0
  angel3_serialize: ^4.0.0
  angel3_code_buffer: ^2.0.0
  build: ^2.0.1
  build_config: ^1.0.0
  code_builder: ^4.0.0
  meta: ^1.3.0
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.0.0
  quiver: ^3.0.1
  logging: ^1.0.0
dev_dependencies:
  build_runner: ^2.0.1
  collection: ^1.15.0
  lints: ^1.0.0
  test: ^1.17.4
