name: angel_serialize_generator
version: 3.0.0
description: Model serialization generators, designed for use with Angel. Combine with angel_serialize for flexible modeling.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/serialize
publish_to: none
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  analyzer: ">=0.27.1 <2.0.0"
  angel_model:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/model
  angel_serialize:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x
      path: packages/serialize/angel_serialize
  build: ">=0.12.0 <2.0.0"
  build_config: ">=0.3.0 <2.0.0"
  code_buffer: ^1.0.0
  code_builder: ^3.0.0
  meta: ^1.3.0
  path: ^1.8.0
  recase: ^2.0.0
  source_gen: ^0.9.0
  quiver: ^2.1.5
dev_dependencies:
  build_runner: ^1.11.5
  collection: ^1.15.0
  pedantic: ^1.11.0
  test: ^1.16.5
# dependency_overrides:
#   angel_serialize:
#     path: ../angel_serialize