name: jael3_preprocessor
version: 8.0.0
description: A pre-processor for resolving blocks and includes within Jael templates.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/angel/tree/master/packages/jael/jael_preprocessor
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  file: ^7.0.0
  jael3: ^8.0.0
  belatuk_symbol_table: ^5.0.0
  collection: ^1.17.0
dev_dependencies:
  belatuk_code_buffer: ^5.0.0
  test: ^1.24.0
  lints: ^2.1.0
# dependency_overrides:
#   jael3:
#     path: ../jael
