name: angel3_migration
version: 8.2.2
description: The abstract classes for implementing database migration in Angel3 framework. Designed to work with Angel3 ORM.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dart-backend/angel/tree/master/packages/orm/angel_migration
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  angel3_orm: ^8.0.0
dev_dependencies:
  lints: ^4.0.0
# dependency_overrides:
#    angel3_orm:
#      path: ../angel_orm
